apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cleanup-job
  labels:
    app.kubernetes.io/name: helm-cronjob
    helm.sh/chart: helm-cronjob
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cleanup-container
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
              - /bin/bash
              - -c
              - ps -ef &
              - sleep 10
          restartPolicy: OnFailure
