apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cleanup
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cleanup
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              command: {{ .Values.command }}
          restartPolicy: OnFailure
